/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export enum storagemodelsv2ComponentStatus {
    COMPONENT_STATUS_UNSPECIFIED = 'COMPONENT_STATUS_UNSPECIFIED',
    COMPONENT_STATUS_INITIALIZING = 'COMPONENT_STATUS_INITIALIZING',
    COMPONENT_STATUS_AVAILABLE = 'COMPONENT_STATUS_AVAILABLE',
    COMPONENT_STATUS_DEGRADED = 'COMPONENT_STATUS_DEGRADED',
    COMPONENT_STATUS_UNAVAILABLE = 'COMPONENT_STATUS_UNAVAILABLE',
    COMPONENT_STATUS_MAINTENANCE = 'COMPONENT_STATUS_MAINTENANCE',
}
