/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export enum v2AnnouncementType {
    ANNOUNCEMENT_TYPE_UNSPECIFIED = 'ANNOUNCEMENT_TYPE_UNSPECIFIED',
    ANNOUNCEMENT_TYPE_ORGA = 'ANNOUNCEMENT_TYPE_ORGA',
    ANNOUNCEMENT_TYPE_RELEASE = 'ANNOUNCEMENT_TYPE_RELEASE',
    ANNOUNCEMENT_TYPE_UPDATE = 'ANNOUNCEMENT_TYPE_UPDATE',
    ANNOUNCEMENT_TYPE_MAINTENANCE = 'ANNOUNCEMENT_TYPE_MAINTENANCE',
    ANNOUNCEMENT_TYPE_BLOG = 'ANNOUNCEMENT_TYPE_BLOG',
}
