/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export enum v2ExternalRelationVariant {
    EXTERNAL_RELATION_VARIANT_UNSPECIFIED = 'EXTERNAL_RELATION_VARIANT_UNSPECIFIED',
    EXTERNAL_RELATION_VARIANT_URL = 'EXTERNAL_RELATION_VARIANT_URL',
    EXTERNAL_RELATION_VARIANT_IDENTIFIER = 'EXTERNAL_RELATION_VARIANT_IDENTIFIER',
    EXTERNAL_RELATION_VARIANT_CUSTOM = 'EXTERNAL_RELATION_VARIANT_CUSTOM',
}
