/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export enum v2InternalRelationVariant {
    INTERNAL_RELATION_VARIANT_UNSPECIFIED = 'INTERNAL_RELATION_VARIANT_UNSPECIFIED',
    INTERNAL_RELATION_VARIANT_BELONGS_TO = 'INTERNAL_RELATION_VARIANT_BELONGS_TO',
    INTERNAL_RELATION_VARIANT_ORIGIN = 'INTERNAL_RELATION_VARIANT_ORIGIN',
    INTERNAL_RELATION_VARIANT_VERSION = 'INTERNAL_RELATION_VARIANT_VERSION',
    INTERNAL_RELATION_VARIANT_METADATA = 'INTERNAL_RELATION_VARIANT_METADATA',
    INTERNAL_RELATION_VARIANT_POLICY = 'INTERNAL_RELATION_VARIANT_POLICY',
    INTERNAL_RELATION_VARIANT_DELETED = 'INTERNAL_RELATION_VARIANT_DELETED',
    INTERNAL_RELATION_VARIANT_CUSTOM = 'INTERNAL_RELATION_VARIANT_CUSTOM',
}
