/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export enum v2PersonalNotificationVariant {
    PERSONAL_NOTIFICATION_VARIANT_UNSPECIFIED = 'PERSONAL_NOTIFICATION_VARIANT_UNSPECIFIED',
    PERSONAL_NOTIFICATION_VARIANT_ACCESS_REQUESTED = 'PERSONAL_NOTIFICATION_VARIANT_ACCESS_REQUESTED',
    PERSONAL_NOTIFICATION_VARIANT_PERMISSION_GRANTED = 'PERSONAL_NOTIFICATION_VARIANT_PERMISSION_GRANTED',
    PERSONAL_NOTIFICATION_VARIANT_PERMISSION_REVOKED = 'PERSONAL_NOTIFICATION_VARIANT_PERMISSION_REVOKED',
    PERSONAL_NOTIFICATION_VARIANT_PERMISSION_UPDATED = 'PERSONAL_NOTIFICATION_VARIANT_PERMISSION_UPDATED',
    PERSONAL_NOTIFICATION_VARIANT_ANNOUNCEMENT = 'PERSONAL_NOTIFICATION_VARIANT_ANNOUNCEMENT',
}
