/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export enum v2TriggerType {
    TRIGGER_TYPE_UNSPECIFIED = 'TRIGGER_TYPE_UNSPECIFIED',
    TRIGGER_TYPE_HOOK_ADDED = 'TRIGGER_TYPE_HOOK_ADDED',
    TRIGGER_TYPE_RESOURCE_CREATED = 'TRIGGER_TYPE_RESOURCE_CREATED',
    TRIGGER_TYPE_LABEL_ADDED = 'TRIGGER_TYPE_LABEL_ADDED',
    TRIGGER_TYPE_STATIC_LABEL_ADDED = 'TRIGGER_TYPE_STATIC_LABEL_ADDED',
    TRIGGER_TYPE_HOOK_STATUS_CHANGED = 'TRIGGER_TYPE_HOOK_STATUS_CHANGED',
    TRIGGER_TYPE_OBJECT_FINISHED = 'TRIGGER_TYPE_OBJECT_FINISHED',
}
