export enum Colors {
    Primary = "primary",
    Secondary = "secondary",
    Success = "success",
    Info = "info",
    Warning = "warning",
    Danger = "danger",
    Light = "light",
    Dark = "dark",
    White = "white",
    Muted = "muted",
    Blue = "blue",
    Azure = "azure",
    Indigo = "indigo",
    Purple = "purple",
    Pink = "pink",
    Red = "red",
    Orange = "orange",
    Yellow = "yellow",
    Lime = "lime",
    Green = "green",
    Teal = "teal",
    Cyan = "cyan",
    None = "none",
}